/* Generated by tools/ra/generate_tmc_memory_map.py. */
#ifndef TMC_RA_MEMORY_MANIFEST_GENERATED_H
#define TMC_RA_MEMORY_MANIFEST_GENERATED_H
#include <stdint.h>
#define TMC_RA_MEMORY_MANIFEST_SHA256 "ac01bf3b7e31c38eb0cb38a4cf8deadc587d71a99c394005a631c64fba2dae5b"
#define TMC_RA_MEMORY_MANIFEST_ENTRY_COUNT 30u
typedef struct { const char* symbol; uint32_t gba_virtual; uint32_t ra_physical; uint32_t gba_bytes; uint8_t reviewed; } TmcRaMemoryManifestEntry;
static const TmcRaMemoryManifestEntry kTmcRaMemoryManifest[] = {
    {"gOAMControls", 0x03000000u, 0x00000u, 1056u, 1u},
    {"gActiveItems", 0x03000b80u, 0x00b80u, 112u, 1u},
    {"gRoomControls", 0x03000bf0u, 0x00bf0u, 52u, 1u},
    {"gScreen", 0x03000f50u, 0x00f50u, 124u, 1u},
    {"gFadeControl", 0x03000fd0u, 0x00fd0u, 26u, 1u},
    {"gInput", 0x03000ff0u, 0x00ff0u, 8u, 1u},
    {"gMain", 0x03001000u, 0x01000u, 14u, 1u},
    {"gRoomTransition", 0x030010a0u, 0x010a0u, 176u, 1u},
    {"gRand", 0x03001150u, 0x01150u, 4u, 1u},
    {"gPlayerEntity", 0x03001160u, 0x01160u, 136u, 1u},
    {"gAuxPlayerEntities", 0x030011e8u, 0x011e8u, 0u, 0u},
    {"gEntities", 0x030015a0u, 0x015a0u, 0u, 0u},
    {"gEntityLists", 0x03003d70u, 0x03d70u, 72u, 1u},
    {"gPlayerState", 0x03003f80u, 0x03f80u, 176u, 1u},
    {"gMessage", 0x02000050u, 0x08050u, 32u, 1u},
    {"gMenu", 0x02000080u, 0x08080u, 0u, 0u},
    {"gIntroState", 0x02000080u, 0x08080u, 0u, 0u},
    {"gChooseFileState", 0x02000080u, 0x08080u, 0u, 0u},
    {"gBgAnimations", 0x02000cc0u, 0x08cc0u, 64u, 1u},
    {"gSave", 0x02002a40u, 0x0aa40u, 0u, 0u},
    {"gMapDataTopSpecial", 0x02002f00u, 0x0af00u, 16384u, 1u},
    {"gHUD", 0x0200af00u, 0x12f00u, 0u, 0u},
    {"gMapTop", 0x0200b650u, 0x13650u, 49156u, 1u},
    {"gRoomMemory", 0x02024050u, 0x2c050u, 64u, 1u},
    {"gMapBottom", 0x02025eb0u, 0x2deb0u, 49156u, 1u},
    {"gUI", 0x02032ec0u, 0x3aec0u, 0u, 0u},
    {"gArea", 0x02033a90u, 0x3ba90u, 0u, 0u},
    {"gRoomVars", 0x02034350u, 0x3c350u, 204u, 1u},
    {"gPauseMenuOptions", 0x02034490u, 0x3c490u, 0u, 0u},
    {"gScriptExecutionContextArray", 0x02036570u, 0x3e570u, 1152u, 1u},
};
#endif
