#!/usr/bin/env python3
"""Deterministically derive the reviewed P2A manifest from linker.ld."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ASSIGNMENT = re.compile(r"\.\s*=\s*0x([0-9A-Fa-f]+)\s*;\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\.")
REGIONS = {
    "iwram": (0x03000000, 0x08000, 0x00000),
    "ewram": (0x02000000, 0x40000, 0x08000),
}

def linker_addresses(path):
    return {name: int(address, 16) for address, name in ASSIGNMENT.findall(path.read_text())}

def manifest_entries(source, addresses):
    entries = []
    for item in source["symbols"]:
        name, region = item["name"], item["region"]
        if name not in addresses:
            raise ValueError(f"{name}: absent from linker.ld")
        if region not in REGIONS:
            raise ValueError(f"{name}: invalid region {region}")
        base, length, physical_base = REGIONS[region]
        offset = addresses[name]
        if offset >= length:
            raise ValueError(f"{name}: linker offset outside {region}")
        entry = dict(item)
        entry["gba_virtual"] = base + offset
        entry["ra_physical"] = physical_base + offset
        entries.append(entry)
    return entries

def manifest_hash(source, entries):
    payload = json.dumps({"version": source["version"], "entries": entries}, sort_keys=True,
                         separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()

def header_text(entries, digest):
    lines = [
        "/* Generated by tools/ra/generate_tmc_memory_map.py. */",
        "#ifndef TMC_RA_MEMORY_MANIFEST_GENERATED_H",
        "#define TMC_RA_MEMORY_MANIFEST_GENERATED_H",
        "#include <stdint.h>",
        f'#define TMC_RA_MEMORY_MANIFEST_SHA256 "{digest}"',
        f"#define TMC_RA_MEMORY_MANIFEST_ENTRY_COUNT {len(entries)}u",
        "typedef struct { const char* symbol; uint32_t gba_virtual; uint32_t ra_physical; uint32_t gba_bytes; uint8_t reviewed; } TmcRaMemoryManifestEntry;",
        "static const TmcRaMemoryManifestEntry kTmcRaMemoryManifest[] = {",
    ]
    for entry in entries:
        size = entry["size"] or 0
        reviewed = 1 if entry["status"] == "reviewed" else 0
        lines.append(f'    {{"{entry["name"]}", 0x{entry["gba_virtual"]:08x}u, 0x{entry["ra_physical"]:05x}u, {size}u, {reviewed}u}},')
    return "\n".join(lines + ["};", "#endif", ""])

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--linker", default="linker.ld")
    parser.add_argument("--source", default="tools/ra/tmc_memory_manifest.json")
    parser.add_argument("--output", default="port/ra/tmc_ra_memory_manifest.generated.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = json.loads(Path(args.source).read_text())
    entries = manifest_entries(source, linker_addresses(Path(args.linker)))
    text = header_text(entries, manifest_hash(source, entries))
    output = Path(args.output)
    if args.check:
        if not output.exists() or output.read_text() != text:
            raise SystemExit("generated manifest is stale")
    else:
        output.write_text(text)

if __name__ == "__main__":
    main()
