#!/usr/bin/env python3
"""Generate the checked-in Casual memory attestation from proven S0 parity."""

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path

from compare_tmc_ra_snapshot import CaptureError, compare, read_capture


FORMAT_VERSION = 1
GAME_ID = 559
CONSOLE_ID = 5
SNAPSHOT_BYTES = 0x58000


class AttestationError(ValueError):
    """Raised when capture evidence cannot produce a production attestation."""


def _ranges(bitmap):
    result = []
    start = None
    for offset, value in enumerate(bitmap):
        if value not in (0, 1):
            raise AttestationError("native validity bitmap must contain only 0 or 1")
        if value and start is None:
            start = offset
        elif not value and start is not None:
            result.append((start, offset - start))
            start = None
    if start is not None:
        result.append((start, len(bitmap) - start))
    if not result:
        raise AttestationError("native validity bitmap selects no bytes")
    return result


def _evidence_digest(native, reference):
    digest = hashlib.sha256()
    digest.update(b"tmc-ra-casual-attestation-v1\0")
    for capture in (native, reference):
        digest.update(
            json.dumps(
                capture["metadata"], sort_keys=True, separators=(",", ":")
            ).encode("utf-8")
        )
        for name in ("snapshot.bin", "provenance.bin", "validity.bin"):
            digest.update(hashlib.sha256(capture[name]).digest())
    return digest.hexdigest()


def generate(native_directory, reference_directory):
    try:
        native = read_capture(native_directory, "native")
        reference = read_capture(reference_directory, "reference")
        result = compare(native, reference, None, validated_scope=True)
    except CaptureError as error:
        raise AttestationError(str(error)) from error

    metadata = native["metadata"]
    if (
        result["result"] != "PASS"
        or result["scope"] != "native-validated-scope-not-requested"
        or metadata.get("state") != "S0"
        or metadata.get("checkpoint") != "boot/title"
        or metadata.get("snapshot_bytes") != SNAPSHOT_BYTES
    ):
        raise AttestationError("evidence is not an exact S0 validated-scope PASS")

    ranges = _ranges(native["validity.bin"])
    selected = sum(size for _, size in ranges)
    if selected != result["selected"]:
        raise AttestationError("validated byte count disagrees with comparison")

    rom_md5 = metadata.get("rom_md5")
    manifest_sha256 = metadata.get("manifest_sha256")
    return {
        "rom_md5": rom_md5,
        "manifest_sha256": manifest_sha256,
        "validity_sha256": hashlib.sha256(native["validity.bin"]).hexdigest(),
        "evidence_sha256": _evidence_digest(native, reference),
        "selected": selected,
        "ranges": ranges,
    }


def render(attestation):
    ranges = attestation["ranges"]
    lines = [
        "/* Generated by tools/ra/generate_tmc_ra_casual_attestation.py. */",
        "#ifndef TMC_RA_CASUAL_ATTESTATION_GENERATED_H",
        "#define TMC_RA_CASUAL_ATTESTATION_GENERATED_H",
        "#include <stdint.h>",
        f"#define TMC_RA_CASUAL_ATTESTATION_VERSION {FORMAT_VERSION}u",
        f"#define TMC_RA_CASUAL_GAME_ID {GAME_ID}u",
        f"#define TMC_RA_CASUAL_CONSOLE_ID {CONSOLE_ID}u",
        f"#define TMC_RA_CASUAL_SNAPSHOT_BYTES 0x{SNAPSHOT_BYTES:x}u",
        f"#define TMC_RA_CASUAL_SELECTED_BYTES {attestation['selected']}u",
        f"#define TMC_RA_CASUAL_RANGE_COUNT {len(ranges)}u",
        f'#define TMC_RA_CASUAL_ROM_MD5 "{attestation["rom_md5"]}"',
        f'#define TMC_RA_CASUAL_MEMORY_MANIFEST_SHA256 "{attestation["manifest_sha256"]}"',
        f'#define TMC_RA_CASUAL_VALIDITY_SHA256 "{attestation["validity_sha256"]}"',
        f'#define TMC_RA_CASUAL_EVIDENCE_SHA256 "{attestation["evidence_sha256"]}"',
        "typedef struct { uint32_t address; uint32_t size; } TmcRaCasualRange;",
        "static const TmcRaCasualRange kTmcRaCasualRanges[] = {",
    ]
    lines.extend(
        f"    {{0x{address:05x}u, 0x{size:x}u}}," for address, size in ranges
    )
    lines.extend(["};", "#endif", ""])
    return "\n".join(lines)


def write_atomic(path, text):
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="ascii",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            delete=False,
        ) as stream:
            temporary = Path(stream.name)
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    except OSError as error:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise AttestationError(f"cannot write {destination}: {error}") from error


def self_test():
    bitmap = bytes((0, 1, 1, 0, 1, 0))
    assert _ranges(bitmap) == [(1, 2), (4, 1)]
    try:
        _ranges(bytes((0, 2)))
    except AttestationError:
        pass
    else:
        raise AssertionError("non-binary validity accepted")
    print("generate_tmc_ra_casual_attestation: ALL PASS")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--native", type=Path)
    parser.add_argument("--reference", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test:
        self_test()
        return 0
    if not args.native or not args.reference or not args.output:
        parser.error("--native, --reference, and --output are required")

    try:
        text = render(generate(args.native, args.reference))
        if args.check:
            if not args.output.exists() or args.output.read_text(encoding="ascii") != text:
                raise AttestationError("generated attestation is stale")
        else:
            write_atomic(args.output, text)
    except (AttestationError, OSError, UnicodeError) as error:
        print(f"FAIL: {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
